index:
    path: /
    controller: App\Controller\DefaultController::index

login:
  path: /login

logout:
  path: /logout

home:
  path: /home
  controller: App\Controller\QuizController::home

listQuestions:
  path: /teacher/question
  controller: App\Controller\QuizController::listQuestions

deleteQuestion:
   path: /teacher/question/delete/{questionId}
   controller: App\Controller\QuizController::deleteQuestion
   methods: [DELETE]

deleteAnswer:
   path: /teacher/question/answer/delete/{answerId}
   controller: App\Controller\QuizController::deleteAnswer
   methods: [DELETE]

editQuestion:
  path: /teacher/question/edit/{questionId}
  controller: App\Controller\QuizController::editQuestion

createQuestion:
  path: /teacher/question/create
  controller: App\Controller\QuizController::createQuestion

listExams:
  path: /teacher/exam
  controller: App\Controller\QuizController::listExams

createExam:
  path: /teacher/exam/create
  controller: App\Controller\QuizController::createExam

editExamQuestions:
  path: /teacher/exam/edit/questions/{examId}
  controller: App\Controller\QuizController::editExamQuestions

editExamStudents:
  path: /teacher/exam/edit/students/{examId}
  controller: App\Controller\QuizController::editExamStudents

deleteExam:
  path: /teacher/exam/delete/{examId}
  controller: App\Controller\QuizController:deleteExam

addQuestionsToExam:
  path: /teacher/exam/create/questions/{examId}
  controller: App\Controller\QuizController::addQuestionsToExam

addStudentsToExam:
  path: /teacher/exam/create/students/{examId}
  controller: App\Controller\QuizController::addStudentsToExam

showTeacherResultsList:
  path: /teacher/showResults
  controller: App\Controller\QuizController::showTeacherResultsList

showTeacherDetailedResult:
  path: /teacher/showResult/{userExamId}
  controller: App\Controller\QuizController::showTeacherDetailedResult

listAvailableExams:
  path: /student/availableExams
  controller: App\Controller\QuizController::listAvailableExams

takeExam:
  path: /student/takeExam/{userExamId}
  controller: App\Controller\QuizController::takeExam

detailedExamResult:
  path: /student/takeExam/result/{userExamId}
  controller: App\Controller\QuizController::detailedExamResult

listStudentsResults:
  path: /student/showResults
  controller: App\Controller\QuizController::listStudentsResults