index:
    path: /
    controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\QuizController::home

listQuestions:
  path: /teacher/question
  controller: App\Controller\QuizController::listQuestions

createQuestionForm:
  path: /teacher/question/create
  controller: App\Controller\QuizController::createQuestionForm

deleteQuestion:
   path: /teacher/question/delete/{questionId}
   controller: App\Controller\QuizController::deleteQuestion
   methods: [DELETE]

login:
  path: /login

logout:
  path: /logout