index:
    path: /
    controller: App\Controller\DefaultController::index

home:
  path: /home
  controller: App\Controller\QuizController::home

listQuestions:
  path: /teacher/question
  controller: App\Controller\QuizController::listQuestions

createQuestion:
  path: /teacher/question/create
  controller: App\Controller\QuizController::createQuestion

login:
  path: /login

logout:
  path: /logout